# Generated by Django 5.1.1 on 2024-09-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='employee_photos/'),
        ),
    ]
